[package]
name = "nes_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
bitflags = "1.3.2"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "frame_time"
harness = false
